on:
  push:
    tags: 
      - "v*"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load Cache For Node
        uses: actions/cache@v2
        with: 
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock', 'package.json') }}
      
      - name: Build
        run: |
          yarn
          yarn run build
          
      - name: Check Out TagName
        id: checkout-tagname
        shell: "python3 {0}"
        run: |
          import os
          import re
          ref = os.getenv('GITHUB_REF', '')
          match = re.search(r'refs\/tags\/(.*)', ref)
          tag_name = match[1] if match is not None else ''
          print('::set-output name=tag_name::'+tag_name)
          
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"


