on:
  push:
    tags: 
      - "v*"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load Cache For Node
        uses: actions/cache@v2
        with: 
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock', 'package.json') }}
      
      - name: Build
        run: |
          yarn
          yarn run build
          cp dist/april-comment.js dist/index.js
          cp dist/april-comment.js dist/index.js.map
          cp dist/april-comment.css dist/index.css
          cp dist/april-comment.css dist/index.css.map
          
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
